[versions]
agp = "9.4.0"
android-compileSdk = "37"
android-minSdk = "26"
android-targetSdk = "37"
androidx-activityCompose = "1.13.0"
androidx-lifecycle = "2.11.0"
componentsResources = "1.12.0"
compose-multiplatform = "1.12.0"
datastore = "1.2.1"
desugar_jdk_libs = "2.1.5"
foundation = "1.12.0"
htmlconverter = "1.1.1"
kmpaletteCore = "3.1.0"
kotlin = "2.4.10"
kotlinx-coroutines = "1.11.0"
kotlinxDatetime = "0.8.0"
kotlinxDatetimeNames = "0.2.0"
kotlinxSerializationJson = "1.11.0"
ksoup = "0.2.6"
ktor = "3.5.2"
landscapistCoil3 = "2.11.0"
logging = "2.1.2"
material3 = "1.9.0"
materialKolor = "5.0.1"
room = "2.8.4"
rssparser = "6.1.8"
ksp = "2.3.6"
navigationCompose = "2.9.2"
material3Android = "1.4.0"
runtime = "1.12.0"
sqlite = "2.7.0"
uiToolingPreview = "1.12.0"
multiplatform-nav3-ui = "1.1.1"
slf4j = "2.0.17-0"

[libraries]
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3Android" }
jetbrains-navigation3-ui = { module = "org.jetbrains.androidx.navigation3:navigation3-ui", version.ref = "multiplatform-nav3-ui" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "componentsResources" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "foundation" }
htmlconverter = { module = "be.digitalia.compose.htmlconverter:htmlconverter", version.ref = "htmlconverter" }
kmpalette-core = { module = "com.kmpalette:kmpalette-core", version.ref = "kmpaletteCore" }
kmpalette-network = { module = "com.kmpalette:extensions-network", version.ref = "kmpaletteCore" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-datetime-names = { module = "io.github.adrcotfas:kotlinx-datetime-names", version.ref = "kotlinxDatetimeNames" }
ksoup = { module = "com.fleeksoft.ksoup:ksoup-network", version.ref = "ksoup" }
logging = { module = "com.diamondedge:logging", version.ref = "logging" }
material-kolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolor" }
material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
landscapist-coil3 = { module = "com.github.skydoves:landscapist-coil3", version.ref = "landscapistCoil3" }
rssparser = { module = "com.prof18.rssparser:rssparser", version.ref = "rssparser" }
runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "runtime" }
slf4j-android = { module = "uk.uuid.slf4j:slf4j-android", version.ref = "slf4j" }
ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "uiToolingPreview" }
ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "uiToolingPreview" }

[plugins]
androidMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
androidx-room = { id = 'androidx.room', version.ref = "room" }