[versions]
agp = "9.0.0"
android-compileSdk = "36"
android-minSdk = "26"
android-targetSdk = "36"
androidx-activityCompose = "1.12.2"
androidx-lifecycle = "2.9.6"
componentsResources = "1.10.0"
compose-multiplatform = "1.10.0"
datastore = "1.2.0"
foundation = "1.10.0"
htmlconverter = "1.1.0"
kmpaletteCore = "3.1.0"
kotlin = "2.3.0"
kotlinx-coroutines = "1.10.2"
kotlinxDatetime = "0.7.1"
kotlinxSerializationJson = "1.10.0"
ksoup = "0.2.5"
ktor = "3.4.0"
landscapistCoil3 = "2.8.3"
logging = "2.1.0"
material3 = "1.9.0"
materialKolor = "4.1.0"
room = "2.8.4"
rssparser = "6.1.2"
#runtimeAndroid = "1.10.1"
ksp = "2.3.4"
navigationCompose = "2.9.1"
material3Android = "1.4.0"
runtime = "1.10.0"
sqlite = "2.6.2"
uiToolingPreview = "1.10.0"

[libraries]
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3Android" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "componentsResources" }
foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "foundation" }
htmlconverter = { module = "be.digitalia.compose.htmlconverter:htmlconverter", version.ref = "htmlconverter" }
kmpalette-core = { module = "com.kmpalette:kmpalette-core", version.ref = "kmpaletteCore" }
kmpalette-network = { module = "com.kmpalette:extensions-network", version.ref = "kmpaletteCore" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
ksoup = { module = "com.fleeksoft.ksoup:ksoup-network", version.ref = "ksoup" }
logging = { module = "com.diamondedge:logging", version.ref = "logging" }
material-kolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolor" }
material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
landscapist-coil3 = { module = "com.github.skydoves:landscapist-coil3", version.ref = "landscapistCoil3" }
rssparser = { module = "com.prof18.rssparser:rssparser", version.ref = "rssparser" }
runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "runtime" }
ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "uiToolingPreview" }
ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "uiToolingPreview" }
#androidx-runtime-android = { group = "androidx.compose.runtime", name = "runtime-android", version.ref = "runtimeAndroid" }
#androidx-material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3Android" }

[plugins]
androidMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
androidx-room = { id = 'androidx.room', version.ref = "room" }